[General]
#################### General ####################

ScreenWidth="1920"
ScreenHeight="1080"
ScreenPadding=""

FontSize="13"
KeyboardSize="0.4"
RoundCorners="8"

Locale=""
HourFormat="HH:mm"
DateFormat="dddd, d MMMM yyyy"

HeaderText="TOP SECRET // RESTRICTED ACCESS"

#################### Background ####################

BackgroundPlaceholder=""
Background="Backgrounds/agency.png"
BackgroundSpeed=""
PauseBackground=""
DimBackground="0.30"
CropBackground="true"
BackgroundHorizontalAlignment="center"
BackgroundVerticalAlignment="center"

#################### Colors ####################

HeaderTextColor="#69ADF4"
DateTextColor="#548CC4"
TimeTextColor="#69ADF4"

FormBackgroundColor="#080F1E"
BackgroundColor="#080F1E"
DimBackgroundColor="#080F1E"

LoginFieldBackgroundColor="#0E1B33"
PasswordFieldBackgroundColor="#0E1B33"
LoginFieldTextColor="#C9E2FF"
PasswordFieldTextColor="#C9E2FF"
UserIconColor="#69ADF4"
PasswordIconColor="#69ADF4"

PlaceholderTextColor="#54749E"
WarningColor="#FF5577"

LoginButtonTextColor="#0B0D0D"
LoginButtonBackgroundColor="#69ADF4"
SystemButtonsIconsColor="#548CC4"
SessionButtonTextColor="#548CC4"
VirtualKeyboardButtonTextColor="#548CC4"

DropdownTextColor="#C9E2FF"
DropdownSelectedBackgroundColor="#69ADF4"
DropdownBackgroundColor="#0E1B33"

HighlightTextColor="#0B0D0D"
HighlightBackgroundColor="#69ADF4"
HighlightBorderColor="#1E3A5F"

HoverUserIconColor="#C9E2FF"
HoverPasswordIconColor="#C9E2FF"
HoverSystemButtonsIconsColor="#69ADF4"
HoverSessionButtonTextColor="#69ADF4"
HoverVirtualKeyboardButtonTextColor="#69ADF4"

#################### Form ####################

PartialBlur="true"
FullBlur=""
BlurMax="32"
Blur=""

HaveFormBackground="false"
FormPosition="left"

#################### Virtual Keyboard ####################

VirtualKeyboardPosition="center"

#################### Interface Behavior ####################

HideVirtualKeyboard="false"
HideSystemButtons="false"
HideLoginButton="false"

ForceLastUser="true"
PasswordFocus="true"
HideCompletePassword="true"
AllowEmptyPassword="false"
AllowUppercaseLettersInUsernames="false"
BypassSystemButtonsChecks="false"
RightToLeftLayout="false"

#################### Translation ####################

TranslatePlaceholderUsername="AGENT ID"
TranslatePlaceholderPassword="ACCESS CODE"
TranslateLogin="AUTHENTICATE"
TranslateLoginFailedWarning="ACCESS DENIED"
TranslateCapslockWarning="CAPS LOCK ON"
TranslateSuspend="Suspend"
TranslateHibernate="Hibernate"
TranslateReboot="Reboot"
TranslateShutdown="Shutdown"
TranslateSessionSelection=""
TranslateVirtualKeyboardButtonOn=""
TranslateVirtualKeyboardButtonOff=""
